/** ISO code → country name, extracted from world-pacific.svg. */
export const WORLD_COUNTRY_NAMES: Record<string, string> = {
  AE: `United Arab Emirates`,
  AF: `Afghanistan`,
  AG: `Antigua and Barbuda`,
  AI: `Anguilla`,
  AL: `Albania`,
  AM: `Armenia`,
  AO: `Angola`,
  AR: `Argentina`,
  AS: `American Samoa`,
  AT: `Austria`,
  AU: `Australia`,
  AW: `Aruba`,
  AZ: `Azerbaijan`,
  BA: `Bosnia and Herzegovina`,
  BB: `Barbados`,
  BD: `Bangladesh`,
  BE: `Belgium`,
  BF: `Burkina Faso`,
  BG: `Bulgaria`,
  BH: `Bahrain`,
  BI: `Burundi`,
  BJ: `Benin`,
  BL: `Saint-Barthélemy`,
  BM: `Bermuda`,
  BN: `Brunei Darussalam`,
  BO: `Bolivia`,
  BQBO: `Netherlands`,
  BQSA: `Saba (Netherlands)`,
  BQSE: `St. Eustatius (Netherlands)`,
  BR: `Brazil`,
  BS: `Bahamas`,
  BT: `Bhutan`,
  BW: `Botswana`,
  BY: `Belarus`,
  BZ: `Belize`,
  CA: `Canada`,
  CD: `Democratic Republic of the Congo`,
  CF: `Central African Republic`,
  CG: `Republic of Congo`,
  CH: `Switzerland`,
  CI: `Côte d'Ivoire`,
  CL: `Chile`,
  CM: `Cameroon`,
  CN: `China`,
  CO: `Colombia`,
  CR: `Costa Rica`,
  CU: `Cuba`,
  CV: `Cape Verde`,
  CW: `Curaçao`,
  CY: `Cyprus`,
  CZ: `Czech Republic`,
  DE: `Germany`,
  DJ: `Djibouti`,
  DK: `Denmark`,
  DM: `Dominica`,
  DO: `Dominican Republic`,
  DZ: `Algeria`,
  EC: `Ecuador`,
  EE: `Estonia`,
  EG: `Egypt`,
  EH: `Western Sahara`,
  ER: `Eritrea`,
  ES: `Spain`,
  ET: `Ethiopia`,
  FI: `Finland`,
  FJ: `Fiji`,
  FK: `Falkland Islands`,
  FM: `Federated States of Micronesia`,
  FO: `Faeroe Islands`,
  FR: `France`,
  GA: `Gabon`,
  GB: `United Kingdom`,
  GD: `Grenada`,
  GE: `Georgia`,
  GF: `French Guiana`,
  GH: `Ghana`,
  GL: `Greenland`,
  GM: `The Gambia`,
  GN: `Guinea`,
  GP: `Guadeloupe`,
  GQ: `Equatorial Guinea`,
  GR: `Greece`,
  GT: `Guatemala`,
  GU: `Guam`,
  GW: `Guinea-Bissau`,
  GY: `Guyana`,
  HN: `Honduras`,
  HR: `Croatia`,
  HT: `Haiti`,
  HU: `Hungary`,
  IC: `Canary Islands (Spain)`,
  ID: `Indonesia`,
  IE: `Ireland`,
  IL: `Israel`,
  IN: `India`,
  IQ: `Iraq`,
  IR: `Iran`,
  IS: `Iceland`,
  IT: `Italy`,
  JM: `Jamaica`,
  JO: `Jordan`,
  JP: `Japan`,
  KE: `Kenya`,
  KG: `Kyrgyzstan`,
  KH: `Cambodia`,
  KM: `Comoros`,
  KN: `Saint Kitts and Nevis`,
  KP: `Dem. Rep. Korea`,
  KR: `Republic of Korea`,
  KW: `Kuwait`,
  KY: `Cayman Islands`,
  KZ: `Kazakhstan`,
  LA: `Lao PDR`,
  LB: `Lebanon`,
  LC: `Saint Lucia`,
  LK: `Sri Lanka`,
  LR: `Liberia`,
  LS: `Lesotho`,
  LT: `Lithuania`,
  LU: `Luxembourg`,
  LV: `Latvia`,
  LY: `Libya`,
  MA: `Morocco`,
  MD: `Moldova`,
  ME: `Montenegro`,
  MF: `Saint-Martin`,
  MG: `Madagascar`,
  MH: `Marshall Islands`,
  MK: `Macedonia`,
  ML: `Mali`,
  MM: `Myanmar`,
  MN: `Mongolia`,
  MP: `Northern Mariana Islands`,
  MQ: `Martinique`,
  MR: `Mauritania`,
  MS: `Montserrat`,
  MT: `Malta`,
  MU: `Mauritius`,
  MV: `Maldives`,
  MW: `Malawi`,
  MX: `Mexico`,
  MY: `Malaysia`,
  MZ: `Mozambique`,
  NA: `Namibia`,
  NC: `New Caledonia`,
  NE: `Niger`,
  NG: `Nigeria`,
  NI: `Nicaragua`,
  NL: `Netherlands`,
  NO: `Norway`,
  NP: `Nepal`,
  NR: `Nauru`,
  NZ: `New Zealand`,
  OM: `Oman`,
  PA: `Panama`,
  PE: `Peru`,
  PF: `French Polynesia`,
  PG: `Papua New Guinea`,
  PH: `Philippines`,
  PK: `Pakistan`,
  PL: `Poland`,
  PR: `Puerto Rico`,
  PS: `Palestine`,
  PT: `Portugal`,
  PW: `Palau`,
  PY: `Paraguay`,
  QA: `Qatar`,
  RE: `Reunion`,
  RO: `Romania`,
  RS: `Serbia`,
  RU: `Russian Federation`,
  RW: `Rwanda`,
  SA: `Saudi Arabia`,
  SB: `Solomon Islands`,
  SC: `Seychelles`,
  SD: `Sudan`,
  SE: `Sweden`,
  SI: `Slovenia`,
  SK: `Slovakia`,
  SL: `Sierra Leone`,
  SN: `Senegal`,
  SO: `Somalia`,
  SR: `Suriname`,
  SS: `South Sudan`,
  ST: `São Tomé and Principe`,
  SV: `El Salvador`,
  SX: `Sint Maarten`,
  SY: `Syria`,
  SZ: `Swaziland`,
  TC: `Turks and Caicos Islands`,
  TD: `Chad`,
  TG: `Togo`,
  TH: `Thailand`,
  TJ: `Tajikistan`,
  TL: `Timor-Leste`,
  TM: `Turkmenistan`,
  TN: `Tunisia`,
  TO: `Tonga`,
  TR: `Turkey`,
  TT: `Trinidad and Tobago`,
  TV: `Tuvalu`,
  TW: `Taiwan`,
  TZ: `Tanzania`,
  UA: `Ukraine`,
  UG: `Uganda`,
  US: `United States`,
  UY: `Uruguay`,
  UZ: `Uzbekistan`,
  VC: `Saint Vincent and the Grenadines`,
  VE: `Venezuela`,
  VG: `British Virgin Islands`,
  VI: `United States Virgin Islands`,
  VN: `Vietnam`,
  VU: `Vanuatu`,
  WS: `Samoa`,
  XK: `Kosovo`,
  YE: `Yemen`,
  YT: `Mayotte`,
  ZA: `South Africa`,
  ZM: `Zambia`,
  ZW: `Zimbabwe`,
};
